#!/bin/bash
set -a

PROJECT="${PROJECT:-spryker}"
IMAGE="${IMAGE:-claranet/spryker-demoshop}"
VERSION=${VERSION:-$(cat $WORKDIR/VERSION)}

# list of variables, which will get autogenerated passwords filled in
AUTOGENERATED_SECRETS="YVES_SESSION_REDIS_PASSWORD ZED_SESSION_REDIS_PASSWORD STORAGE_REDIS_PASSWORD RABBITMQ_PASSWORD"

# use this to add docker build arguemnts like --build-arg=GITLAB_TOKEN=xxxx (from claranet/php base image)
DOCKER_BUILD_ARGS=""
DOCKERFILE="$WORKDIR/Dockerfile"
